
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://brunogabriel.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

# baseurl: /personal-jekyll-theme

# Google tracking id to track your visitors
#google-tracking-id: "UA-35880426-4"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "pt-BR"
author: "Bruno Gabriel dos Santos"
title: "{ Bruno Gabriel }"
description: "Analista de Sistemas"
keywords: "brunogabriel, github, system analyst, mobile, software engineer, developer, programmer, android, python, java"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/mario-bg.png"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Há uma força motriz mais poderosa que o vapor, a eletricidade e a energia atômica: a vontade - Albert Einstein"
  - text: "Para toda ação existe uma reação - Isaac Newton"

me-img: "/img/profile_image.jpg"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 30

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "brunogabrieldossantos"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/simova_logo.png"
    date: "Setembro 2015 - Hoje"
    description: "Analista de Sistemas na Simova Tecnologia e Serviços de Informática"
  - image: "/img/timeline/phocus_logo.png"
    date: "Março 2014 - Agosto 2015"
    description: "Analista e Desenvolvedor Mobile Pleno na Phocus Interact"
  - image: "/img/timeline/fapesp_logo.png"
    date: "Novembro 2012 - Outubro 2013"
    description: "Bolsista Pesquisador da Fundação de Amparo à Pesquisa do Estado de São Paulo (FAPESP)"
  - image: "/img/timeline/cnpq_logo.png"
    date: "Dezembro 2011 - Novembro 2012"
    description: "Bolsista Pesquisador do Conselho Nacional de Desenvolvimento Científico e Tecnológico (CNPq)"
  - image: "/img/timeline/unifesp_logo.png"
    date: "Março 2010 - Janeiro de 2014 - "
    description: "Graduação em Ciência da Computação na Universidade Federal de São Paulo (UNIFESP)"

# First image of the Timeline

timeline-img: "/img/timeline/child.png"

###########
# Contact #
###########

email: "bruno.gsantos89@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Bruno atua como Analista de Sistemas, principalmente com tecnologias mobile e web. Nas horas vagas arrisca correr e se exercitar, mas também não deixa de lado uma partida de futebol, basquete e video game."
author_blurb_image: "/img/profile_image.jpg"

##################
# Social Buttons #
##################

social:
  - title: "github"
    url: "https://github.com/brunogabriel"
  - title: "bitbucket"
    url: "https://bitbucket.org/brunogabriel/"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/bruno-gabriel-dos-santos-473b0671"
  - title: "envelope"
    url: "mailto:bruno.gsantos89@gmail.com"

############
# 404 page #
############

404-img: "/img/deckfailcat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  Sobre: 'about'
  Blog: 'latest-post'
  Carreira: 'timeline'
  Contato: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
